import 'poligonosapp';
import '@types/jquery';
import 'postcss-scss';
import '@types/geojson';
import '@types/leaflet';
import './loading-example';
import './loading-controller';
import './polygons';
import '@types/node';
declare module '*.css';
declare module '*.ts';
